services:
  - type: web
    name: invoicesgenius-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: invoicesgenius.settings
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        sync: false

  - type: worker
    name: invoicesgenius-celery
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: celery -A invoicesgenius worker --loglevel=debug
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: invoicesgenius.settings
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
