services:
  - type: web
    name: invoicegenius-web
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn invoicegenius.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: invoicegenius.settings
      - key: SECRET_KEY
        value: your-secret
      - key: DATABASE_URL
        fromDatabase:
          name: invoicegenius-db
          property: connectionString

  - type: worker
    name: invoicegenius-celery
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: celery -A invoicegenius worker --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: invoicegenius.settings
      - key: SECRET_KEY
        value: your-secret
