# Generated by Django 5.2.4 on 2025-07-31 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_processing_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='parsedinvoicedata',
            options={'verbose_name': 'Parsed Invoice Data', 'verbose_name_plural': 'Parsed Invoice Data'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='original_file',
            field=models.FileField(help_text='Original uploaded invoice file', upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processed',
            field=models.BooleanField(default=False, help_text='Flag to indicate if OCR and AI parsing have completed'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when processing finished', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the invoice was uploaded'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(help_text='Owner of this invoice', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parsedinvoicedata',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency code (e.g., USD, EUR)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parsedinvoicedata',
            name='invoice',
            field=models.OneToOneField(help_text='Invoice this parsed data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='parsedinvoicedata',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date on the invoice', null=True),
        ),
        migrations.AlterField(
            model_name='parsedinvoicedata',
            name='line_items',
            field=models.JSONField(blank=True, help_text='List of line items, each with details like description, quantity, price', null=True),
        ),
        migrations.AlterField(
            model_name='parsedinvoicedata',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount on the invoice', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parsedinvoicedata',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total invoice amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parsedinvoicedata',
            name='vendor',
            field=models.CharField(blank=True, help_text='Vendor or supplier name', max_length=255, null=True),
        ),
    ]
