# Generated by Django 5.2.4 on 2025-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_invoices_in_status_cec546_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
