# Generated by Django 5.2.4 on 2025-08-06 08:31

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='original_file',
            field=models.FileField(help_text='Original uploaded invoice file', storage=storages.backends.s3.S3Storage(), upload_to='invoices/'),
        ),
    ]
